name: build

on:
  push:
    branches:
      - "master"
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1

      - name: Prepare for publishing
        run: npm run out:prepare

      - name: create env file
        run: |
          touch .env
          echo NODE_ENV=production >> .env
          echo GH_TOKEN=${{ secrets.GH_TOKEN }} >> .env

      - name: Build/release Electron app
        env:
          NODE_ENV: production
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: npm run publish
